# Nerve Agent Configuration
# Author: mmwei3 (2025-10-28)
# Wethers: cloudWays

# Server configuration
server:
  url: "http://localhost:8090/api"
  timeout: 30s
  
# Authentication
auth:
  token: ""  # Will be set via command line

# Heartbeat
heartbeat:
  interval: 30s
  timeout: 10s

# Collection
collection:
  cpu: true
  memory: true
  disk: true
  network: true
  gpu: true
  ipmi: true
  
# Task
task:
  timeout: 300s
  max_concurrent: 5
  
# Logging
log:
  level: info  # debug, info, warn, error
  output: stderr
  
# Update
update:
  enabled: true
  check_interval: 1h
  auto_update: false

